### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by bettercallazamat** [Zubenna/new-york-times-page#2]
## Good start. Improvements suggestions:
1. head should be header instead
2. most popular articles section should not be aside element
3. do not use figcaption without figure
4. get rid of fixed width and height in iframes
5. img in nav bar should be a link
6. use classed divs for wrapping paragraphs
7. try not using h4 tags inside p tags
8. Wrap whole article with article tag
Keep good work.

**Comment by Zubenna** [comment]
suggestions implemented
