### ISSUE TITLE
Team 95 Peer To Peer Review: 06/03/2020

### ISSUE THREAD

**Issue by jamezjaz** [Zubenna/new-york-times-page#4]
Remarks and Suggestions:
1.Don’t use reset file while the universal selector for padding and margin equal to zero are also in use.
2.The reset.css file link should be above the style.css file link in the html.
2.It’s better not to assign class to main element instead just target the main straight up.
5.Avoid repetition of css properties for a particular selector.
6.Figcaption element should always go with figure element and not small element.

**Comment by Zubenna** [comment]
Recommendations has been implemented
