### ISSUE TITLE
Team 95 Peer To Peer Review: 11/03/2020

### ISSUE THREAD

**Issue by Maclenn77** [Zubenna/new-york-times-page#5]
**Remark & Suggestions:**

- Problem combining rem and percentages in the same structure, maybe this is causing that some elements overlap

- Try to use "min" or "max" height or width

- Since Ln153, many classes for unique elements

- Many unnecessary classes

- Don't need to specify parent class in Ln74

- Try not repeat properties and use more general rules

- Reading the code is hard because is messy

**That's all, folks!**

**Comment by Zubenna** [comment]
Corrections implemented
