### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by rootDEV2990** [Zubenna/new-york-times-page#6]
Awesome well done!! Congrats on the project approval. Maybe for next time try...
Looks a lot like new your times good job.

-checking your indentations. 
-try nav in footer.
-hr tag should help only divide sections maybe try border in CSS instead. 
-logo on header maybe could be centered with absolute positioning. 
-absolute can help but careful with right and left properties to help responsive. 
-try aside instead of div for most pop section.
-more position sec position absolute instead of fixed for responsive aid. 
-grid can help also target responsive issues.
-article tag could be divided by sections within same article. 
-Html has divs only one child maybe div is not needed.

Good job!! 
-

**Comment by Zubenna** [comment]
Noted
